### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/KTX#14]
I would like to point out that an identifier like "[`_KTX_H_`](https://github.com/KhronosGroup/KTX/blob/bcd0c29d777543f799ed4f0394dc0671b23c8c25/include/ktx.h#L4)" [does not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by msc-** [comment]
I'll consider it. Please send a pull request with a proposal. Remember that the guard define must be unlikely to be used bu a user of the KTX library.  That is why is has a non-compliant leading '_'.

**Comment by elfring** [comment]
There are other possibilities to [improve the affected source code](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?").
* How do you think about to add a prefix?
* Would you like to make [include guards](https://en.wikipedia.org/wiki/Include_guard#Difficulties "Coherent naming scheme for include guards") unique by appending [a kind of UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier "universally unique identifier")?

**Comment by msc-** [comment]
I think appending a UUID is the answer. Any prefix still risks conflicting with a user program.

**Comment by elfring** [comment]
Are you going to [delete the leading underscore](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoid undefined behaviour?") in affected identifiers?

**Comment by msc-** [comment]
Yes, as that is the non-compliant part. Please submit a pull request with what you think is a good solution.

**Comment by msc-** [comment]
This has been fixed. Closing.
