### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [KhronosGroup/KTX#15]
Would you like to [replace any double quotes](https://github.com/KhronosGroup/KTX/blob/c3f42078c6f56f1b8dd193dcf7cb88f7b6531e4f/lib/ktxfilestream.c#L47 "Check header file inclusion style") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by msc-** [comment]
No. My intention in using double quotes is to indicate that the headers come from within the project rather than from the system header locations. Perhaps that meaning is too non-obvious as, since neither `KHR/khrplatform.h` nor `ktx.h` are in the same folder as the including files, the double quotes do not actually direct the compiler to do anything usefully different here. But I see no compelling reason to change.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by msc-** [comment]
The project files use -I options in the compile commands that point to the directories containing the subject include files. So the only additional search is of the directory containing the source file. The -iquote option I believe is gcc specific otherwise I should use that instead of -I.

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
* Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
* Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?
