### ISSUE TITLE
GL_TEXTURE_CUBE_MAP_ARRAY

### ISSUE THREAD

**Issue by mre4ce** [KhronosGroup/KTX#17]
KTX/lib/checkheader.c currently states:

/* Check texture dimensions. KTX files can store 8 types of textures:
	   1D, 2D, 3D, cube, and array variants of these. There is currently
	   no GL extension that would accept 3D array or cube array textures. */

However, GL_TEXTURE_CUBE_MAP_ARRAY has been OpenGL core since 4.0 and we've had GL_EXT_texture_cube_map_array for OpenGL ES 3.1 since 2014.

**Comment by msc-** [comment]
Support added. Closing. Thanks for the report.

**Comment by mre4ce** [comment]
Great thanks Mark!
