### ISSUE TITLE
Closed Bugzilla for KTX to new bugs

### ISSUE THREAD

**Issue by oddhack** [KhronosGroup/KTX#31]
Mark, FYI I closed down the (long inactive) public KTX Bugzilla to *new* bugs (there is one remaining open bug, many years old), and directed people to use this repo instead. Bugzilla got another spammer attack today and we're trying to lock down everything that's not actually getting used.

**Comment by msc-** [comment]
Thanks Jon. The README.md in this repo already says to use GitHub issues, so closing this.
